language: c
os:
  - osx
  - linux
compiler:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
  - release
matrix:
  fast_finish: true
notifications:
  email: false
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CONDA_OS='Linux'; else CONDA_OS='MacOSX'; fi;
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-${CONDA_OS}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$CC numpy pandas scipy matplotlib pytest sympy pip pytz
  - source activate test-environment
  - pip install -r requirements_test.txt
  - python setup.py -q install
script:
  - py.test . -v --cov-report html --cov=chemicals --cov-report term-missing -m "not online and not thermo and not numba"
after_success:
  - coveralls
