# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    List,
    Optional,
)


def LK_omega(Tb: float, Tc: float, Pc: float) -> float: ...


def Stiel_polar_factor(Psat: float, Pc: float, omega: float) -> float: ...


def omega(CASRN: str, method: Optional[str] = ...) -> Optional[float]: ...


def omega_definition(Psat: float, Pc: float) -> float: ...


def omega_methods(CASRN: str) -> List[str]: ...

__all__: List[str]