# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Dict,
    Optional,
    Union,
)


def HHV_modified_Dulong(mass_fractions: Dict[str, float]) -> float: ...


def HHV_stoichiometry(
    stoichiometry: Dict[str, float],
    Hf: float,
    Hf_chemicals: None = ...
) -> float: ...


def LHV_from_HHV(HHV: float, N_H2O: float) -> float: ...


def as_atoms(formula: Union[str, Dict[str, float], Dict[str, int]]) -> Dict[str, float]: ...


def combustion_data(
    formula: Union[Dict[str, float], str, Dict[str, int]],
    Hf: Optional[int] = ...,
    MW: None = ...,
    method: Optional[str] = ...
) -> CombustionData: ...


def combustion_stoichiometry(atoms: Dict[str, float], MW: None = ...) -> Dict[str, float]: ...


class CombustionData:
    @property
    def LHV(self) -> float: ...

__all__: List[str]