# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    List,
    Optional,
)


def __getattr__(name: str): ...


def _load_dipole_data() -> None: ...


def dipole_moment(CASRN: str, get_methods: bool = ..., method: Optional[str] = ...) -> float: ...


def dipole_moment_methods(CASRN: str) -> List[str]: ...

__all__: List[str]