# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Union


def EQ100(
    T: float,
    A: float = ...,
    B: float = ...,
    C: float = ...,
    D: float = ...,
    E: float = ...,
    F: int = ...,
    G: int = ...,
    order: Union[complex, float, int] = ...
) -> float: ...


def EQ101(T: int, A: float, B: float, C: float, D: float, E: int) -> float: ...


def EQ102(
    T: float,
    A: float,
    B: float,
    C: float,
    D: float,
    order: Union[complex, float, int] = ...
) -> float: ...


def EQ104(
    T: float,
    A: float,
    B: float,
    C: int,
    D: float,
    E: float,
    order: Union[complex, float, int] = ...
) -> float: ...


def EQ105(T: float, A: float, B: float, C: float, D: float) -> float: ...


def EQ106(T: int, Tc: float, A: float, B: float, C: float = ..., D: float = ..., E: float = ...) -> float: ...


def EQ107(
    T: float,
    A: float = ...,
    B: float = ...,
    C: float = ...,
    D: float = ...,
    E: float = ...,
    order: Union[complex, float, int] = ...
) -> float: ...


def EQ114(
    T: float,
    Tc: float,
    A: float,
    B: float,
    C: float,
    D: float,
    order: Union[complex, float, int] = ...
) -> float: ...


def EQ115(T: int, A: float, B: float, C: float = ..., D: float = ..., E: int = ...) -> float: ...


def EQ116(
    T: float,
    Tc: float,
    A: float,
    B: float,
    C: float,
    D: float,
    E: float,
    order: Union[complex, float, int] = ...
) -> float: ...


def EQ127(
    T: float,
    A: float,
    B: float,
    C: float,
    D: float,
    E: float,
    F: float,
    G: float,
    order: Union[complex, float, int] = ...
) -> float: ...

__all__: List[str]