# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from numpy import float64
from pandas.core.frame import DataFrame
from typing import (
    List,
    Optional,
    Union,
)


def GWP(
    CASRN: str,
    get_methods: bool = ...,
    method: Optional[str] = ...
) -> Optional[Union[float64, List[str], float]]: ...


def ODP(
    CASRN: str,
    get_methods: bool = ...,
    method: Optional[str] = ...
) -> Optional[Union[float64, float, str, List[str]]]: ...


def __getattr__(name: str) -> DataFrame: ...


def _load_GWP_ODP_data() -> None: ...


def _load_logP_data() -> None: ...


def logP(CASRN: str, get_methods: bool = ..., method: Optional[str] = ...) -> Optional[Union[List[str], float]]: ...

__all__: List[str]