# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from pandas.core.frame import DataFrame
from typing import (
    List,
    Optional,
    Union,
)


def GWP(CASRN: str, method: Optional[str] = ...) -> Optional[float]: ...


def GWP_methods(CASRN: str) -> List[str]: ...


def ODP(CASRN: str, method: Optional[str] = ...) -> Optional[Union[str, float]]: ...


def ODP_methods(CASRN: str) -> List[str]: ...


def __getattr__(name: str) -> DataFrame: ...


def _load_GWP_ODP_data() -> None: ...


def _load_logP_data() -> None: ...


def logP(CASRN: str, method: Optional[str] = ...) -> Optional[float]: ...


def logP_methods(CASRN: str) -> List[str]: ...

__all__: List[str]