# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from pandas.core.frame import DataFrame
from typing import (
    List,
    Optional,
    Union,
)


def API10A32(T: float, Tc: float, K_W: float) -> float: ...


def Aleem(T: float, MW: float, Tb: float, rhol: float, Hvap_Tb: float, Cpl: float) -> float: ...


def Brock_Bird(T: float, Tb: float, Tc: float, Pc: float) -> float: ...


def Diguilio_Teja(T: float, xs: List[float], sigmas_Tb: List[float], Tbs: List[float], Tcs: List[float]) -> float: ...


def Hakim_Steinberg_Stiel(T: float, Tc: float, Pc: float, omega: float, StielPolar: float = ...) -> float: ...


def Jasper(T: float, a: int, b: float) -> float: ...


def Mersmann_Kind_surface_tension(
    T: float,
    Tm: float,
    Tb: float,
    Tc: float,
    Pc: float,
    n_associated: int = ...
) -> float: ...


def Meybodi_Daryasafar_Karimi(rho_water: int, rho_oil: int, T: int, Tc: int) -> float: ...


def Miqueu(T: float, Tc: float, Vc: float, omega: float) -> float: ...


def Pitzer(T: float, Tc: float, Pc: float, omega: float) -> float: ...


def REFPROP_sigma(
    T: float,
    Tc: float,
    sigma0: float,
    n0: float,
    sigma1: float = ...,
    n1: float = ...,
    sigma2: float = ...,
    n2: float = ...
) -> float: ...


def Sastri_Rao(T: float, Tb: float, Tc: float, Pc: float, chemicaltype: Optional[str] = ...) -> float: ...


def Somayajulu(T: int, Tc: float, A: float, B: float, C: float) -> float: ...


def Weinaug_Katz(parachors: List[float], Vml: float, Vmg: float, xs: List[float], ys: List[float]) -> float: ...


def Winterfeld_Scriven_Davis(xs: List[float], sigmas: List[float], rhoms: List[float]) -> float: ...


def Zuo_Stenby(T: float, Tc: float, Pc: float, omega: float) -> float: ...


def __getattr__(name: str) -> DataFrame: ...


def load_interface_dfs() -> None: ...


def sigma_IAPWS(T: float) -> float: ...

__all__: List[str]