# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from pandas.core.frame import DataFrame
from typing import (
    Dict,
    List,
    Optional,
    Tuple,
    Union,
)


def __getattr__(
    name: str
) -> Union[Dict[str, Union[Dict[str, Union[str, float, List[float], List[Optional[float]]]], Dict[str, Union[str, float, List[float]]]]], DataFrame]: ...


def _load_CRC_data() -> None: ...


def _load_VDI_saturation_dict() -> None: ...


def lookup_VDI_tabular_data(
    CASRN: str,
    prop: str
) -> Union[Tuple[List[float], List[float]], Tuple[List[float], List[float]]]: ...

__all__: List[str]