# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from pandas.core.frame import DataFrame


def __getattr__(name: str) -> DataFrame: ...


def _load_permittivity_data() -> None: ...


def permittivity_IAPWS(T: float, rho: float) -> float: ...

__all__: List[str]