# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from pandas.core.frame import DataFrame
from typing import (
    List,
    Optional,
    Tuple,
    Union,
)


def RI(CASRN: str, method: Optional[str] = ...) -> Tuple[float, float]: ...


def RI_IAPWS(T: float, rho: float, wavelength: float = ...) -> float: ...


def RI_from_molar_refractivity(Rm: float, Vm: float) -> float: ...


def RI_methods(CASRN: str) -> List[str]: ...


def RI_to_brix(RI: float) -> float: ...


def __getattr__(name: str) -> DataFrame: ...


def _load_RI_data() -> None: ...


def brix_to_RI(brix: float) -> float: ...


def molar_refractivity_from_RI(RI: float, Vm: float) -> float: ...


def polarizability_from_RI(RI: float, Vm: float) -> float: ...

__all__: List[str]