# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    List,
    Optional,
    Union,
)


def Henry_converter(
    val: float,
    old_scale: str,
    new_scale: str,
    rhom: Optional[float] = ...,
    MW: Optional[float] = ...
) -> float: ...


def Henry_pressure(
    T: float,
    A: float,
    B: float = ...,
    C: float = ...,
    D: float = ...,
    E: float = ...,
    F: float = ...
) -> float: ...


def Henry_pressure_mixture(Hs: List[Optional[float]], weights: None = ..., zs: Optional[List[float]] = ...) -> float: ...


def Tm_depression_eutectic(
    Tm: float,
    Hm: int,
    x: Optional[float] = ...,
    M: Optional[float] = ...,
    MW: Optional[float] = ...
) -> float: ...


def solubility_eutectic(
    T: float,
    Tm: float,
    Hm: float,
    Cpl: int = ...,
    Cps: int = ...,
    gamma: float = ...
) -> float: ...


def solubility_parameter(T: float, Hvapm: float, Vml: float) -> Optional[float]: ...

__all__: List[str]