# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Union


def ITS90_68_difference(T: float) -> float: ...


def T_converter(T: float, current: str, desired: str) -> float: ...


def build_splines() -> None: ...

__all__: List[str]