# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from pandas.core.frame import DataFrame
from typing import (
    List,
    Optional,
    Union,
)


def Bahadori_gas(T: float, MW: int) -> float: ...


def Bahadori_liquid(T: float, M: int) -> float: ...


def Chung(T: float, MW: float, Tc: float, omega: float, Cvm: float, mu: float) -> float: ...


def Chung_dense(
    T: float,
    MW: float,
    Tc: float,
    Vc: float,
    omega: float,
    Cvm: float,
    Vm: float,
    mu: float,
    dipole: float,
    association: float = ...
) -> float: ...


def DIPPR9B(
    T: float,
    MW: float,
    Cvm: float,
    mu: float,
    Tc: Optional[float] = ...,
    chemtype: Optional[str] = ...
) -> float: ...


def DIPPR9G(T: float, P: float, Tc: float, Pc: float, kl: float) -> float: ...


def DIPPR9H(ws: List[float], ks: List[float]) -> float: ...


def DIPPR9I(zs: List[float], Vms: List[float], ks: List[float]) -> float: ...


def Eli_Hanley(T: float, MW: float, Tc: float, Vc: float, Zc: float, omega: float, Cvm: float) -> float: ...


def Eli_Hanley_dense(
    T: float,
    MW: float,
    Tc: float,
    Vc: float,
    Zc: float,
    omega: float,
    Cvm: float,
    Vm: float
) -> float: ...


def Eucken(MW: float, Cvm: float, mu: float) -> float: ...


def Eucken_modified(MW: float, Cvm: float, mu: float) -> float: ...


def Filippov(ws: List[float], ks: List[float]) -> float: ...


def Gharagheizi_gas(T: float, MW: float, Tb: float, Pc: float, omega: float) -> float: ...


def Gharagheizi_liquid(T: int, M: int, Tb: int, Pc: float, omega: float) -> float: ...


def Lakshmi_Prasad(T: float, M: int) -> float: ...


def Lindsay_Bromley(
    T: float,
    ys: List[float],
    ks: List[float],
    mus: List[float],
    Tbs: List[float],
    MWs: List[float]
) -> float: ...


def Mersmann_Kind_thermal_conductivity_liquid(T: int, MW: float, Tc: float, Vc: float, na: int) -> float: ...


def Missenard(T: float, P: float, Tc: float, Pc: float, kl: float) -> float: ...


def Nicola(T: int, M: float, Tc: float, Pc: float, omega: float) -> float: ...


def Nicola_original(T: int, M: float, Tc: float, omega: float, Hfus: int) -> float: ...


def Sato_Riedel(T: int, M: int, Tb: int, Tc: int) -> float: ...


def Sheffy_Johnson(T: int, M: int, Tm: int) -> float: ...


def Stiel_Thodos_dense(T: float, MW: float, Tc: float, Pc: float, Vc: float, Zc: float, Vm: float, kg: float) -> float: ...


def Wassiljewa_Herning_Zipperer(
    zs: List[float],
    ks: List[float],
    MWs: Union[List[int], List[float]],
    MW_roots: Optional[List[float]] = ...
) -> float: ...


def __getattr__(name: str) -> DataFrame: ...


def _load_k_data() -> None: ...


def k_IAPWS(
    T: float,
    rho: float,
    Cp: Optional[float] = ...,
    Cv: Optional[float] = ...,
    mu: Optional[float] = ...,
    drho_dP: Optional[float] = ...
) -> float: ...

__all__: List[str]