# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from pandas.core.frame import DataFrame
from typing import (
    List,
    Optional,
    Union,
)


def Amgat(xs: List[float], Vms: List[float]) -> float: ...


def Bhirud_normal(T: float, Tc: float, Pc: float, omega: float) -> float: ...


def COSTALD(T: float, Tc: float, Vc: float, omega: float) -> float: ...


def COSTALD_compressed(T: float, P: float, Psat: float, Tc: float, Pc: float, omega: float, Vs: float) -> float: ...


def COSTALD_mixture(xs: List[float], T: float, Tcs: List[float], Vcs: List[float], omegas: List[float]) -> float: ...


def CRC_inorganic(T: float, rho0: float, k: float, Tm: float) -> float: ...


def Campbell_Thodos(
    T: float,
    Tb: float,
    Tc: float,
    Pc: float,
    M: float,
    dipole: float = ...,
    hydroxyl: bool = ...
) -> float: ...


def Goodman(T: int, Tt: float, Vml: float) -> float: ...


def Rackett(T: float, Tc: float, Pc: float, Zc: float) -> float: ...


def Rackett_mixture(
    T: float,
    xs: List[float],
    MWs: List[float],
    Tcs: List[float],
    Pcs: List[float],
    Zrs: List[float]
) -> float: ...


def SNM0(T: int, Tc: float, Vc: float, omega: float, delta_SRK: Optional[float] = ...) -> float: ...


def Townsend_Hales(T: int, Tc: float, Vc: float, omega: float) -> float: ...


def Yamada_Gunn(T: int, Tc: float, Pc: float, omega: float) -> float: ...


def __getattr__(name: str) -> DataFrame: ...


def _load_rho_data() -> None: ...


def ideal_gas(T: float, P: float) -> float: ...

__all__: List[str]