name: Pre-commit

# TEMPORARILY DISABLED - uncomment the on: section below and remove workflow_dispatch to re-enable
# on:
#   push:
#     branches: [master, release]
#   pull_request:
#     branches: [master, release]
# workflow_dispatch allows manual triggering from GitHub Actions UI
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/release' }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install prek
      run: |
        python -m pip install --upgrade pip
        pip install prek

    - name: Run prek
      run: prek run --all-files
